Pull request #808: AG-30908  Move cleanup to final task
Merge in ADGUARD-FILTERS/tsurlfilter from feature/AG-30908 to master

Squashed commit of the following:

commit 78e034c04510339896215046d2951811571072db
Author: Vladimir Zhelvis <v.zhelvis@adguard.com>
Date:   Wed Mar 6 14:38:54 2024 +0300

    delete tswebextension smoke tests node_modules

commit 198496c1d0871106b1a13bac050f1b21a619fc01
Author: Vladimir Zhelvis <v.zhelvis@adguard.com>
Date:   Wed Mar 6 14:04:08 2024 +0300

    add final task for cleanup in specs

diff --git a/bamboo-specs/adguard-api-build.yaml b/bamboo-specs/adguard-api-build.yaml
--- a/bamboo-specs/adguard-api-build.yaml
+++ b/bamboo-specs/adguard-api-build.yaml
@@ -42,12 +42,6 @@ Build:
 
             cd packages/adguard-api/
             yarn pack --filename adguard-api.tgz
-            cd ../../
-
-            # cleanup parent
-            rm -rf node_modules
-            # cleanup child packages
-            npx lerna@6 clean -y
     - inject-variables:
         file: ./packages/adguard-api/dist/build.txt
         scope: RESULT
@@ -57,6 +51,27 @@ Build:
         configuration:
           selectedRepository: defaultRepository
           tagName: adguard-api-v${bamboo.inject.version}
+  final-tasks:
+    - script:
+        interpreter: SHELL
+        scripts:
+          - |-
+            set -x
+            set -e
+
+            # Fix mixed logs
+            exec 2>&1
+
+            ls -la
+
+            echo "Size before cleanup:" && du -h | tail -n 1
+            
+            # cleanup parent
+            rm -rf node_modules
+            # cleanup child packages
+            npx lerna@6 clean -y
+  
+            echo "Size after cleanup:" && du -h | tail -n 1
   artifacts:
     - name: adguard-api.tgz
       location: packages/adguard-api/
diff --git a/bamboo-specs/css-tokenizer-build.yaml b/bamboo-specs/css-tokenizer-build.yaml
--- a/bamboo-specs/css-tokenizer-build.yaml
+++ b/bamboo-specs/css-tokenizer-build.yaml
@@ -46,13 +46,6 @@ Build:
             # Pack the CSS Tokenizer package into a tarball
             cd packages/css-tokenizer/
             yarn pack --filename css-tokenizer.tgz
-            cd ../../
-
-            # Cleanup parent
-            rm -rf node_modules
-
-            # Cleanup child packages
-            npx lerna@6 clean -y
     - inject-variables:
         file: ./packages/css-tokenizer/dist/build.txt
         scope: RESULT
@@ -62,6 +55,27 @@ Build:
         configuration:
           selectedRepository: defaultRepository
           tagName: css-tokenizer-v${bamboo.inject.version}
+  final-tasks:
+    - script:
+        interpreter: SHELL
+        scripts:
+          - |-
+            set -x
+            set -e
+
+            # Fix mixed logs
+            exec 2>&1
+
+            ls -la
+
+            echo "Size before cleanup:" && du -h | tail -n 1
+            
+            # cleanup parent
+            rm -rf node_modules
+            # cleanup child packages
+            npx lerna@6 clean -y
+  
+            echo "Size after cleanup:" && du -h | tail -n 1  
   # Store the CSS Tokenizer package tarball as an artifact
   artifacts:
     - name: css-tokenizer.tgz
