Pull request 1417: AG-46378 use the native clean task for each stage
Squashed commit of the following:

commit 6083eb7126bfa3ccbd5219dd712ee3aab62b4cb7
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Fri Sep 19 00:36:50 2025 +0300

    Refine cleanup command in tsurlfilter-tests.yaml to limit depth of removal, enhancing safety during workspace cleanup

commit 8c1a93547d23fa33cf78d3419fa92b9c3bc31734
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Fri Sep 19 00:13:24 2025 +0300

    Implement artifact preservation and enhanced cleanup process in tsurlfilter-tests.yaml

commit 66c58fd3a9bd447f02da9ff79e70425c14d0bd98
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Thu Sep 18 23:24:49 2025 +0300

    Add comment in tsurlfilter-tests.yaml to clarify the use of pnpm clean in jobs with artifacts

commit a31474fb239207ae79be00696ba8124f96a990dc
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Thu Sep 18 23:22:48 2025 +0300

    Add inline shell commands to final-tasks in tsurlfilter-tests.yaml for enhanced cleanup and size reporting

commit c2c23cb57405fba4ea4a5806b53fcf6dab4dbe44
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Thu Sep 18 22:27:48 2025 +0300

    Remove 'clean' task from final-tasks in tsurlfilter-tests.yaml to retain artifacts.

commit 0c50e8fd0a76a05c9ddf66c972dc571a073b0978
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Thu Sep 18 16:45:47 2025 +0300

    Add final tasks to tsurlfilter-tests.yaml for cleanup and size checking

commit 607d8ca597c14f9c34ea2358be8eecd76deb4313
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Thu Sep 18 16:43:33 2025 +0300

    Remove Git diagnostics from tsurlfilter-tests.yaml to streamline the script and improve readability.

commit 1c8961378bcfd8fbb0f94b5e4c9f8189969f422d
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Thu Sep 18 16:36:10 2025 +0300

    Update dockerContainer version in tsurlfilter-tests.yaml from 22.14--0 to 22.17--0

commit fbf00b44fe45cd3380540d41f4968ac6e077b54c
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Thu Sep 18 16:05:38 2025 +0300

    Add Git diagnostics to tsurlfilter-tests.yaml for improved troubleshooting

commit 35a5f33e856963131bffab283f1aae1fa9322d9f
Author: slvvko <v.leleka@adguard.com>
Date:   Thu Sep 18 08:43:08 2025 -0400

    add var for check-size-script

commit eb1462568e4c25932d121cf0e4c9e5e9029b203e
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Thu Sep 18 13:28:08 2025 +0300

    Remove clean tasks section to keep artifacts

commit 9ee9d44323f6ea8c50f9ba208b9ba9f039681dfb
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Thu Sep 18 11:12:34 2025 +0300

    Remove the 'check-size.sh' script as it has been replaced by inline shell commands in the tsurlfilter-tests.yaml for improved visibility of directory size and contents.

commit 30bd5ae8b45f7b9bdec2b46c6ba5970dfcf841b4
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Thu Sep 18 11:05:03 2025 +0300

    Update tsurlfilter-tests.yaml to replace 'check-size.sh' script with inline shell commands for better visibility of directory size and contents.

commit a1b05aa1510a2694806fc83b6ae398ba9f89360d
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Thu Sep 18 11:00:52 2025 +0300

    Remove 'Check size' job from tsurlfilter-tests.yaml

commit 2faec4de1dff835591ed930f7a0cb059c04e16ec
Author: Maxim Topciu <mtopciu@adguard.com>
Date:   Thu Sep 18 10:50:09 2025 +0300

    AG-46378 add check size and clean after each task

commit 9b524116c33856574692b750cb3c857bd6b9bc7f
Author: slvvko <v.leleka@adguard.com>
Date:   Thu Sep 18 00:01:31 2025 -0400

    use the native clean task for each stage

diff --git a/bamboo-specs/tsurlfilter-tests.yaml b/bamboo-specs/tsurlfilter-tests.yaml
--- a/bamboo-specs/tsurlfilter-tests.yaml
+++ b/bamboo-specs/tsurlfilter-tests.yaml
@@ -5,7 +5,7 @@ plan:
   key: TSURLFILTERTEST
   name: tsurlfilter - tests
 variables:
-  dockerContainer: adguard/node-ssh:22.14--0
+  dockerContainer: adguard/node-ssh:22.17--0
   testTimeout: 600s
 
 # Some packages are independent of each other so we can run them in parallel (different jobs on same stage)
@@ -77,11 +77,6 @@ stages:
       <<: *stage
       jobs:
         - Update TSUrlFilter Docs MV3
-  - Cleanup:
-      <<: *stage
-      final: true
-      jobs:
-        - Cleanup
 
 # NOTE: Each script is separate because, otherwise, Bamboo does not fail in the case of an error.
 
@@ -111,6 +106,21 @@ Test Logger:
         interpreter: SHELL
         scripts:
           - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/logger-tests.sh"
+    # IMPORTANT: run clean after each stage
+    # since each stage is run in a separate directory and we want to clean up after each stage
+  final-tasks:
+    - clean
+    - script: &check-size-script
+        interpreter: SHELL
+        scripts:
+          - |-
+            set -ex
+
+            ls -alt
+
+            echo "Current size:" && du -h | tail -n 1
+
+            du -h . | sort -hr | head -n 30
   requirements: &requirements
     - adg-docker: 'true'
     - extension: 'true'
@@ -126,6 +136,9 @@ Test CSSTokenizer:
         interpreter: SHELL
         scripts:
           - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/css-tokenizer-tests.sh"
+  final-tasks:
+    - clean
+    - script: *check-size-script
   requirements: *requirements
 
 Test AGTree:
@@ -139,6 +152,9 @@ Test AGTree:
         interpreter: SHELL
         scripts:
           - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/agtree-tests.sh"
+  final-tasks:
+    - clean
+    - script: *check-size-script
   requirements: *requirements
 
 Test TSUrlFilter:
@@ -151,6 +167,9 @@ Test TSUrlFilter:
         interpreter: SHELL
         scripts:
           - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/tsurlfilter-tests.sh"
+  final-tasks:
+    - clean
+    - script: *check-size-script
   requirements: *requirements
 
 Test TSWebExtension:
@@ -164,6 +183,9 @@ Test TSWebExtension:
         interpreter: SHELL
         scripts:
           - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/tswebextension-tests.sh"
+  final-tasks:
+    - clean
+    - script: *check-size-script
   requirements: *requirements
 
 Test DNR-Rulesets:
@@ -177,6 +199,9 @@ Test DNR-Rulesets:
         interpreter: SHELL
         scripts:
           - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/dnr-rulesets-tests.sh"
+  final-tasks:
+    - clean
+    - script: *check-size-script
   requirements: *requirements
 
 Test Examples - APIs and TSWebExtensions:
@@ -202,6 +227,44 @@ Test Examples - APIs and TSWebExtensions:
         interpreter: SHELL
         scripts:
           - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/examples-adguard-api-mv3-tests.sh"
+  final-tasks:
+    - script:
+        interpreter: SHELL
+        scripts:
+          - |-
+            set -x
+            set -e
+
+            ls -alt
+
+            echo "Current size:" && du -h | tail -n 1
+
+            # Files to preserve (adjust as needed)
+            ARTIFACTS="
+            packages/examples/adguard-api/build/extension.zip
+            packages/examples/adguard-api-mv3/build/extension.zip
+            "
+
+            TMP="$(mktemp -d)"
+            trap 'rm -rf "$TMP"' EXIT
+
+            # Stash artifacts to /tmp
+            for f in $ARTIFACTS; do
+              [ -e "$f" ] || continue
+              mkdir -p "$TMP/$(dirname "$f")"
+              mv "$f" "$TMP/$f"
+            done
+
+            # Clean entire workspace (including dotfiles and .git)
+            find . -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
+
+            # Restore artifacts
+            for f in $ARTIFACTS; do
+              [ -e "$TMP/$f" ] || continue
+              mkdir -p "$(dirname "$f")"
+              mv "$TMP/$f" "$f"
+            done
+    - script: *check-size-script
   artifacts:
     - name: examples-adguard-api-extension.zip
       location: packages/examples/adguard-api/build
@@ -231,42 +294,9 @@ Update TSUrlFilter Docs MV3:
         configuration:
           commitMessage: 'skipci: Automatic update tsurlfilter MV3 docs'
           selectedRepository: defaultRepository
-  requirements: *requirements
-
-Cleanup:
-  key: CLEAN
-  docker: *docker
-  tasks:
-    - checkout
-    - script:
-        interpreter: SHELL
-        scripts:
-          - |-
-            set -x
-            set -e
-
-            # Fix mixed logs
-            exec 2>&1
-
-            ls -la
-
-            echo "Size before cleanup:" && du -h | tail -n 1
-
-            du -h . | sort -hr | head -n 30
-
-            # Check if node_modules directory exists
-            if [ -d "node_modules" ]; then
-              # to run clean commands in the packages
-              pnpm -r clean
-
-              # to remove node_modules
-              pnpm clean
-            else
-              echo "node_modules directory does not exist, skipping pnpm clean"
-            fi
-
-            rm -rf .git
-            echo "Size after cleanup:" && du -h | tail -n 1
+  final-tasks:
+    - clean
+    - script: *check-size-script
   requirements: *requirements
 
 branches:
