Test only affected packages

diff --git a/bamboo-specs/tswebextension-tests.yaml b/bamboo-specs/tswebextension-tests.yaml
--- a/bamboo-specs/tswebextension-tests.yaml
+++ b/bamboo-specs/tswebextension-tests.yaml
@@ -45,6 +45,19 @@ Test:
 
             # Set cache directory
             pnpm config set store-dir ${bamboo.cachePnpm}
+
+            # Run NX CLI to find projects changed since the master branch and check if the specified project is affected.
+            # And store grep exit status to determine if the project was found (0) or not (1).
+            is_affected=$(pnpm dlx nx show projects --affected --select=projects --base=master --head=HEAD | grep -q "@adguard/tswebextension"; echo $?)
+
+            branch="${bamboo.planRepository.branchName}"
+
+            # If not on 'master' and the project is not affected, skip tests for it.
+            if [ "$branch" != "master" ] && [ "$is_affected" -ne 0 ]; then
+              echo "No changes in project, skipping tests"
+              exit 0;
+            fi
+
             pnpm install
 
             # TODO make sure that we use monospace correctly
